[deps]
BayesLaplace = "c52c1a26-f7c5-402b-80be-ba1e638ad478"
CounterfactualExplanations = "2f13d31b-18db-44c1-bc43-ebaf2cff0be0"
GraphRecipes = "bd48cda9-67a9-57be-86fa-5b3c104eda73"
IJulia = "7073ff75-c697-5162-941a-fcdaad2a7d2a"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
MLDatasets = "eb30cadb-4394-5ae3-aed4-317e484a6458"
PlotThemes = "ccf2f8ad-2431-5c83-bf29-c5338b663b6a"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
RCall = "6f49c342-dc21-5d91-9882-a32aef131414"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"
